apiVersion: v1
kind: Service
metadata:
  name: service-groups
spec:
  selector:
    app: service-groups
  type: NodePort
  ports:
    - name: http
      port: 8081
      nodePort: 30001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-groups
spec:
  selector:
    matchLabels:
      app: service-groups
  replicas: 1
  template:
    metadata:
      labels:
        app: service-groups
    spec:
      containers:
        - name: server
          image: legoyoda/service-groups:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8081